/// Victim-portal config: the option lists and the content fingerprint.
///
/// The fingerprint is a CROSS-LANGUAGE CONTRACT. The GCC computes it in
/// Dart to answer "does this node already serve exactly these options?"
/// without pushing first; the node computes the same thing in Python when
/// it stores a config. If the two ever disagree, the GCC quietly reports
/// every node as mismatched forever, and the operator re-pushes for no
/// reason. The expected value below was produced by the node's own
/// backend/mission_config.py content_id().
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:gcc_app/services/portal_config.dart';

void main() {
  group('portal config fingerprint', () {
    test('matches the value the Python node computes for the same options',
        () {
      // Generated by: mission_config.content_id({situations: kGeneric...})
      expect(portalConfigId(situations: kGenericSituations), '4ff157af031b');
    });

    test('identical options give an identical id, so no false mismatch', () {
      expect(portalConfigId(situations: kGenericSituations),
          portalConfigId(situations: List.of(kGenericSituations)));
    });

    test('changing a label changes the id', () {
      final edited = [
        {'id': 'trapped', 'label': 'I am stuck', 'urgent': true},
        ...kGenericSituations.skip(1),
      ];
      expect(portalConfigId(situations: edited),
          isNot(portalConfigId(situations: kGenericSituations)));
    });

    test('changing the headline changes the id', () {
      expect(
        portalConfigId(situations: kGenericSituations, headline: 'Different'),
        isNot(portalConfigId(situations: kGenericSituations)),
      );
    });

    test('the rescuer-visibility flag is part of the fingerprint', () {
      expect(
        portalConfigId(
            situations: kGenericSituations, showRescuerPositions: false),
        isNot(portalConfigId(situations: kGenericSituations)),
      );
    });
  });

  group('suggested options', () {
    test('known disasters get tailored wording', () {
      final flood = suggestedFor('flood');
      expect(flood.any((s) => '${s['label']}'.contains('boat')), isTrue);
      expect(suggestedFor('landslide'),
          isNot(equals(suggestedFor('flood'))));
    });

    test('an unknown disaster falls back to generic, never to nothing', () {
      expect(suggestedFor('meteor strike'), kGenericSituations);
      expect(suggestedFor(''), kGenericSituations);
    });

    test('case and spacing do not matter', () {
      expect(suggestedFor('  FLOOD '), suggestedFor('flood'));
    });

    test('every option has the fields the node validates', () {
      for (final list in [...kSuggestedSituations.values, kGenericSituations]) {
        expect(list.length, inInclusiveRange(1, 12));
        for (final s in list) {
          expect('${s['id']}'.trim(), isNotEmpty);
          expect('${s['label']}'.trim(), isNotEmpty);
          expect('${s['label']}'.length, lessThanOrEqualTo(120));
        }
        expect(list.map((s) => s['id']).toSet().length, list.length,
            reason: 'ids must be unique or the node rejects the push');
      }
    });

    test('every list offers a non-urgent "I am safe" style option', () {
      for (final list in [...kSuggestedSituations.values, kGenericSituations]) {
        expect(list.any((s) => s['urgent'] != true), isTrue,
            reason: 'someone reporting they are fine must have a button too');
      }
    });
  });
}
